### ISSUE TITLE
[enhancement] Increase Randomness of the ball

### ISSUE THREAD

**Issue by t1war1** [jajodiaraghav/Breakout#18]
On playing the game multiple times, anyone can catch the moves by which the game can be won in no time. Increasing randomness will decrease the probability of winning the game by those same moves.

**Comment by t1war1** [comment]
I would like to work on this issue

**Comment by thegauravtiwari** [comment]
@jajodiaraghav sir, for resolving this, I thought of changing dx=-dx and dy=-dy these statements into dx=kdx and dy=mdy where k and m are random numbers, BUT it would be ambiguous as the angle between line of impact and normal before and after collision should be the same :p   . But there is another way of creating randomness by changing the initial position of the paddle. When I played this game long ago, user decided the initial position of paddle and then the ball moves. So, the same should be done here. So, do I need to create another issue for this with title choose initial position or continue with the same?

**Comment by t1war1** [comment]
@jajodiaraghav I've sent PR for settings panel issue. Speed in changed, so now randomness is created as old moves to win the game work no more. So the issue should be closed.
