### ISSUE TITLE
Allow user to save highscore for current session

### ISSUE THREAD

**Issue by jajodiaraghav** [jajodiaraghav/Breakout#3]
Electronjs uses localstorage to store session data, use this to store highscore as long as the session lives

**Comment by terminator1903** [comment]
I am working on this one

**Comment by t1war1** [comment]
Sir the issue isn't resolved. I noticed a test case when the code doesn't work. Can you please open back the request

**Comment by jajodiaraghav** [comment]
@thegauravtiwari I have reopened the issue as per your request. Although, from next time, please open a new issue for such cases.

**Comment by t1war1** [comment]
I've submitted the PR to resolve the issue. Please check it out :)

**Comment by t1war1** [comment]
Sir, I've created the PR again with proper title and package-lock.json added in .gitignore
