### ISSUE TITLE
Add sound to Game

### ISSUE THREAD

**Issue by jajodiaraghav** [jajodiaraghav/Breakout#4]
Play a sound (~500ms)

Possible locations:
- When Game starts, Pauses and resumes
- When lost life

**Comment by vchrombie** [comment]
I have a doubt regarding this issue.

Different sounds for different locations?
I mean four different sounds for four different locations.
Am i right?

**Comment by jajodiaraghav** [comment]
I think 2 different type of sounds would do. One for "life lost" and "dead", other for "Start", "pause" and "resume"

**Comment by vchrombie** [comment]
Okay 
I will work on this issue.

**Comment by vchrombie** [comment]
I am facing problems with the selection.
Which sounds to choose?

Can we add Mario Sounds to our game?

**Comment by jajodiaraghav** [comment]
Something similar:
https://github.com/jajodiaraghav/Snake/tree/master/Assets/Sounds

All I want is a certain short sound that plays when the user loses a life, or breaks a block (You can use this sound too).

**Comment by vchrombie** [comment]
Okay

What about 'Win' and 'Lose'?

**Comment by jajodiaraghav** [comment]
The issue does not mention about win/lose. In case you want to add it, please search for a relevant sound online. You can find plenty.

**Comment by vchrombie** [comment]
Okay

**Comment by jajodiaraghav** [comment]
@vchrombie I just accidentally merged @thegauravtiwari PR as I didn't knew you have claimed this one. I am really sorry about that.
I would recommend you to pull from latest master and test if the sounds work properly. In case you can improve something, send a PR
Thanks!

**Comment by t1war1** [comment]
@vchrombie @jajodiaraghav  I'm really sorry for this. I thought anyone can work on any issue. I'll take care of this in future. Sorry again.

**Comment by vchrombie** [comment]
It's alright. :)
Everyone makes mistakes in life.
Not a big issue @jajodiaraghav @thegauravtiwari 

Anyway, Good job @thegauravtiwari

**Comment by t1war1** [comment]
Thank you @vchrombie :)
