### ISSUE TITLE
Create a settings panel

### ISSUE THREAD

**Issue by jajodiaraghav** [jajodiaraghav/Breakout#5]
The settings panel will allow user to alter the difficulty level.

**Comment by t1war1** [comment]
I would like to work on this issue.

**Comment by t1war1** [comment]
@jajodiaraghav Sir, I want to know what properties of the game need to be changed for different difficulty levels

**Comment by jajodiaraghav** [comment]
I think we can change two properties based on difficulty:
1. Speed of ball
2. Length of the platform

Feel free to mention your idea in case you like.

**Comment by t1war1** [comment]
@jajodiaraghav Thank you
