### ISSUE TITLE
Prevent the board to go out of the frame

### ISSUE THREAD

**Issue by jajodiaraghav** [jajodiaraghav/Breakout#6]

**Comment by t1war1** [comment]
As per my observation, the issue is that when we decrease window size, the game board gets overflowed. So this needs to be resolved. Isn't it?

**Comment by jajodiaraghav** [comment]
We can somehow fix the window size and prevent resizing. This will fix the issue.
One more issue is that soemtimes, even in the default window size, the board/platform goes out of frame.
Are you able to reproduce this?

**Comment by t1war1** [comment]
Yes . I’ll work on this issue
